### PR TITLE
Fixed typo and new APIs

### PR DESCRIPTION
**Pull request by zubfatal**
I've fixed a small typo on the 'streets' API, and added APIs for municipalities, regions and provinces.

### CODE REVIEW

**Comment by nicoeg** [comment]
Hey,
Thanks for the PR. I will give it a look tomorrow :)

**Review by nicoeg — APPROVED** [review]
Looks good, thanks!

**Comment by zubfatal** [comment]
Cool :) wasn't sure if you still actively maintained this.

I was actually working on a project, which need to grab some DAWA data, and i stumbled across this package, which had most of what I needed, except for the stuff I've added, but rather than building something new, I thought i'd give extending your awesome code a shot :)

Will you update your package on packagist.org as well?

**Comment by nicoeg** [comment]
Hehe thanks, glad it can help!
Should be updated on Packagist now :)

**Pull request merged**
